/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsb_ffmpeg_FFmpegNative */

#ifndef _Included_com_hsb_ffmpeg_FFmpegNative
#define _Included_com_hsb_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_com_hsb_ffmpeg_FFmpegNative_test_1h264
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
