/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_llj_ffmpeg_demo_MainActivity */

#ifndef _Included_com_llj_ffmpeg_demo_MainActivity
#define _Included_com_llj_ffmpeg_demo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_llj_ffmpeg_demo_MainActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_llj_ffmpeg_demo_MainActivity_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_llj_ffmpeg_demo_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_llj_ffmpeg_demo_MainActivity_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_llj_ffmpeg_demo_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_llj_ffmpeg_demo_MainActivity_avfilterinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_llj_ffmpeg_demo_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_llj_ffmpeg_demo_MainActivity_configurationinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
